### ISSUE TITLE
Broken hardcoded version

### ISSUE THREAD

**Issue by notsag** [highb/asdf-teleport-ent#25]
**Describe the bug**

teleport-ent v14.2.2 is the only version listed as available and installing other versions fails.

**Steps to reproduce**

```
# .tools-versions
teleport-ent 14.2.3
```

```sh
# Trying to install fails
asdf install teleport-ent
* Downloading teleport-ent release 14.2.3...
tbot: gzip decompression failed (zlib returned error -3, msg invalid code lengths set)
tar: Error exit delayed from previous errors.
asdf-teleport-ent: Could not extract /Users/notsag/.asdf/downloads/teleport-ent/14.2.3/teleport-ent-14.2.3.tar.gz

# list-all shows only 14.2.2
asdf list-all teleport-ent
14.2.2
```

**Expected behavior**

v14.2.3 should listed as available (https://github.com/gravitational/teleport/releases) and installation should succeed

**Screenshots**

**Additional context**

v14.2.2 contains bugs fixed by next version: https://github.com/gravitational/teleport/pull/35576 https://github.com/gravitational/teleport/pull/35545

I fixed it locally by hardcoding the version in the `list_github_tags` functions in  `lib/utils.bash` but removing the test on the `GITHUB_API_TOKEN` fixes it for me (showing all releases available).

**Comment by highb** [comment]
PR Merged, please verify that it fixes the issue for you.
